# Generated by Django 5.0.6 on 2024-07-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_guestbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbook',
            options={'ordering': ['-req_time']},
        ),
        migrations.RenameField(
            model_name='guestbook',
            old_name='time',
            new_name='req_time',
        ),
    ]
