# Generated by Django 5.0.6 on 2024-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_alter_guestbook_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(unique=True)),
                ('build_name', models.CharField(max_length=255)),
                ('cover', models.URLField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('price_num', models.CharField(max_length=50)),
                ('price_unit', models.CharField(max_length=50)),
                ('browsenum', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('callnum', models.IntegerField()),
                ('area', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('photo_num', models.IntegerField()),
                ('build_type', models.CharField(max_length=50)),
                ('build_type_val', models.IntegerField()),
                ('purpose', models.CharField(max_length=50)),
                ('purpose_other2_str', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=255)),
                ('layout', models.CharField(max_length=255)),
                ('build_url', models.URLField(max_length=500)),
                ('tag_type', models.IntegerField()),
            ],
        ),
    ]
