# Generated by Django 5.0.6 on 2024-07-17 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_buildinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RentTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Surrounding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('post_id', models.IntegerField(unique=True)),
                ('price', models.CharField(max_length=255)),
                ('price_unit', models.CharField(max_length=255)),
                ('section_name', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('community', models.CharField(max_length=255)),
                ('room_str', models.CharField(max_length=255)),
                ('is_video', models.BooleanField()),
                ('preferred', models.BooleanField()),
                ('kind', models.IntegerField()),
                ('photo_list', models.ManyToManyField(to='blog_post.photo')),
                ('rent_tag', models.ManyToManyField(to='blog_post.renttag')),
                ('surrounding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog_post.surrounding')),
            ],
        ),
    ]
